[package]
name = "room-turn"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
num_cpus = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
turn-server = { version = "4.1.2", default-features = false, features = ["udp", "tcp"] }
